server:
  port: 9999

spring.application.name: config-client
spring.profiles.active: development
#spring.profiles.active: production

#spring.config.import: optional:configserver:http://root:s3cr3t@localhost:8888
spring.config.import: optional:configserver:http://localhost:8888
spring.cloud.config:
  username: root
  password: s3cr3t
