spring.application.name: kafka-wikimedia-producer

server:
  port: 8082

logging:
  level:
    root: INFO
    com.example.spring: DEBUG

spring:
  kafka.bootstrap-servers: &k-bootstrap-servers localhost:9093

app:
  course:
    kafka:
      bootstrap-servers: *k-bootstrap-servers
      topic: wikimedia.change
      partitions: 3
    open-search:
      scheme: https
      host: localhost
      port: 9200
      username: admin
      password: OPENsearch123!
      index: wikimedia_change
