# This setting controls the switch between modes
spring.profiles.active: @spring.profile.activated@

logging:
  level:
    root: WARN
    com.example.spring.stream: DEBUG
    org.springframework: INFO

# Example settings
## This setting can increase or decrease the rate of message production (1000 = 1s)
## spring.cloud.stream.poller.fixed-delay=1000

## This setting can control which function method in our code will be triggered if there are multiple
## spring.cloud.function.definition=supplyLoan

spring:
  cloud:
    stream:
      function:
        definition: fizzBuzzProducer;fizzBuzzProcessor;fizzBuzzConsumer;pingSupplier;pingConsumer
      # https://docs.spring.io/spring-cloud-stream/docs/3.1.5/reference/html/spring-cloud-stream.html#_polling_configuration_properties
      poller:
        # default is 1000 (1s)
        fixedDelay: 10000
#        timeUnit: MILLISECONDS
#        initialDelay: 0
#        cron: ~
      bindings:
        fizzBuzzProducer-out-0:
          destination: numbers
        fizzBuzzProcessor-in-0:
          destination: numbers
        fizzBuzzProcessor-out-0:
          destination: fizz-buzz
        fizzBuzzConsumer-in-0:
          destination: fizz-buzz
        pingSupplier-out-0:
          destination: ping
        pingConsumer-in-0:
          destination: ping
