scrape_configs:
  - job_name: 'springboot-example-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Spring Boot Example App'
