services:
  mysql:
    image: mysql:5.7
#    image: mysql:5.7.18
    container_name: mysql-liquibase
    ports:
      - 3306:3306
    volumes:
      - liquibase_mysql_data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: liquibase
      MYSQL_USER: liquibase
      MYSQL_PASSWORD: liquibase

volumes:
  liquibase_mysql_data:
    driver: local
