spring.application.name: observability

management.endpoints.web.exposure.include: '*'

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false
