spring.application.name: kafka

logging:
  level:
    root: INFO
    com.example.spring: DEBUG

management.endpoints.web.exposure.include: health,info,bindings

spring:
  kafka:
    bootstrap-servers: &k-bootstrap-servers localhost:9093
    consumer:
      auto-offset-reset: earliest

app:
  kafka-apps:
    words:
      enabled: true
      producers.enabled: false
