spring.application.name: auth-client

logging.level:
  com.example: DEBUG
  org.springframework: INFO
  org.springframework.security: TRACE

# GitHub login
spring.security.oauth2.client.registration:
  github:
    clientId: ""
    clientSecret: ""

