# https://springdoc.org/#springdoc-openapi-core-properties
# https://springdoc.org/#swagger-ui-properties

# Configuration for defining different uris than default ones
springdoc:
  api-docs:
    path: /springdoc/v3/api-docs
  swagger-ui:
    path: /springdoc/swagger-ui.html
    configUrl: /springdoc/v3/api-docs/swagger-config
    oauth2RedirectUrl: /springdoc/swagger-ui/oauth2-redirect.html
    urls:
      - url: /springdoc/v3/api-docs
        name: api-docs