debug: true

logging:
  level:
    ROOT: INFO
    com.example.spring.spring.batch: DEBUG
    com.example.spring.spring.batch.listener.log: DEBUG
    org.springframework: INFO
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.context.annotation: DEBUG
#    org.springframework.core.io.support: DEBUG

app:
  auto-configure: true

spring:
  datasource:
#    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:testdb;sql.enforce_strict_size=true;hsqldb.tx=mvcc
#    username: sa
#    password:
