spring.application.name: batch-playground

spring.profiles.default: h2
spring.docker.compose.enabled: false

debug: true

logging:
  level:
    ROOT: INFO
    com.example.spring.batch: DEBUG
    com.example.spring.batch.playground.batch.listener.log: DEBUG
#    com.example.spring.batch.playground.batch.listener.log: INFO
    org.springframework: INFO
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.context.annotation: DEBUG
#    org.springframework.core.io.support: DEBUG
    #    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

spring.batch:
  # don't auto-start jobs
  job.enabled: false
  # initialize DB
  jdbc.initialize-schema: ALWAYS

app.features:
  user:
    jobs-enabled: true
    data-populator-enabled: true
