#name: kafka

services:

  # https://hub.docker.com/r/bitnami/kafka
  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - type: volume
        source: kafka-data
        target: /bitname/kafka
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      # listeners ::: INTERNAL: Docker and Inter Broker | EXTERNAL: outside Docker | CONTROLLER: broker management
      # NOTE: default internal listener was PLAINTEXT, and this change forces to configure KAFKA_CFG_INTER_BROKER_LISTENER_NAME
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

  # https://hub.docker.com/r/provectuslabs/kafka-ui
  # https://docs.kafka-ui.provectus.io/overview/getting-started
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "9001:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      #      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      #      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      #      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
      #      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      #      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
      DYNAMIC_CONFIG_ENABLED: true
  #    volumes:
  #      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

  # https://hub.docker.com/r/obsidiandynamics/kafdrop
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

volumes:
  kafka-data:
