spring.jpa.properties:
  jakarta.persistence.schema-generation.scripts:
    action: drop-and-create
    create-source: metadata
    create-target: build/classes/java/test/gen/create.sql
    drop-source: metadata
    drop-target: build/classes/java/test/gen/drop.sql
