logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework: INFO


management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false

spring.cloud.openfeign:
  okhttp.enabled: true
  client:
    config:
      default:
        loggerLevel: FULL
      json-placeholder:
        url: https://jsonplaceholder.typicode.com
        loggerLevel: FULL
