# Use root/example as user/password credentials
version: "3.9"

services:

  mongo:
    image: mongo
    container_name: springdata-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: test
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db

  mongo-express:
    image: mongo-express
    container_name: springdata-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"

volumes:
  mongodb-data: