spring.application.name: auth-server

server:
  port: 9000

logging:
  level:
    com.example.spring.auth: debug
    org.springframework.security: trace
    org.springframework: info

app:
#  security-config: properties
#  security-config: java
  security-config: custom-authenticators

springdoc:
  show-oauth2-endpoints: true

spring:
  security:
    user:
      name: user
      password: pass
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret-oidc-cli"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
          messaging-client:
            registration:
              client-id: "messaging-client"
              client-secret: "{noop}secret-msg-cli"
#              client-secret: "{bcrypt}$2a$10$TiiC5Jl.HOjrDvblQ5RNJ.KHBcBFEX17wDA1aLwyFOmk4Qz5lsM26"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client"
                - "http://127.0.0.1:8080/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "message.read"
                - "message.write"
            require-authorization-consent: true
          custom-code-client:
            registration:
              client-id: "custom-code-client"
              client-secret: "{noop}secret-custom-code-cli"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
              authorization-grant-types:
                - "client_credentials"
                - "urn:ietf:params:oauth:grant-type:custom_code"
              scopes:
                - "openid"
                - "profile"
                - "message.read"
                - "message.write"
