spring.application.name: auth-server

server:
  port: 9000

logging:
  level:
    com.example.spring.auth: debug
    org.springframework.security: trace
    org.springframework: info

springdoc:
  show-oauth2-endpoints: true
